// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;
using MyStarStable.Common;

namespace MyStarStable.iOS
{
	public partial class EventTableCell : UITableViewCell
	{
	    private CalendarEvent _event;

	    public CalendarEvent Event
	    {
	        set
	        {
	            _event = value;
	            TitleLabel.Text = _event.Title;
                DateTime localStartDate = _event.StartDate.ToLocalTime();
	            DateTime localEndDate = _event.EndDate.ToLocalTime();
	            if (SelectedTime.Day != localStartDate.Day && SelectedTime.Day != localEndDate.Day)
	            {
	                StartDateLabel.Text = "APP/CAL/ALL_DAY".Localize();
	                EndDateLabel.Text = "";
                }
                else if (SelectedTime.Day == localStartDate.Day && SelectedTime.Day != localEndDate.Day)
                {
                    StartDateLabel.Text = localStartDate.ToShortTimeString();
                    EndDateLabel.Text = "APP/CAL/START_DAY".Localize();
                }
                else if (SelectedTime.Day != localStartDate.Day && SelectedTime.Day == localEndDate.Day)
                {
                    StartDateLabel.Text = "APP/CAL/END_DAY".Localize();
                    EndDateLabel.Text = localEndDate.ToShortTimeString();
                }
	            else
	            {
	                StartDateLabel.Text = localStartDate.ToShortTimeString();
	                EndDateLabel.Text = localEndDate.ToShortTimeString();
	            }
	        }
            get { return _event; }
	    }

	    public DateTime SelectedTime { get; set; }

	    public EventTableCell (IntPtr handle) : base (handle)
		{
		}

        public EventTableCell(string cellId) : base(UITableViewCellStyle.Default, cellId)
        {
        }
	}
}
