// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;
using MyStarStable.Common;

namespace MyStarStable.iOS
{
	public partial class MailTableCell : UITableViewCell
	{
		public MailTableCell (IntPtr handle) : base (handle)
		{
		}

	    public MailTableCell(string cellId) : base(UITableViewCellStyle.Default, cellId)
	    {
	        
	    }

	    private CharacterMailMessage _mailMessage;
	    public CharacterMailMessage MailMessage
	    {
	        get { return _mailMessage; }
	        set
	        {
	            _mailMessage = value;

                SubjectLabel.Text = _mailMessage.Subject;
                SenderLabel.Text = _mailMessage.SenderCharacterName;
                MessageLabel.Text = _mailMessage.Message;
                
                DateTime localSentDate = _mailMessage.SentDate.ToLocalTime();
                DateLabel.Text = localSentDate.ToShortDateString() + " " + localSentDate.ToShortTimeString();

                // Bold/un-bold depending on read status.
	            if (_mailMessage.ReadDate == null)
	            {
	                UIFont oldFont = SubjectLabel.Font;
	                SubjectLabel.Font = UIFont.BoldSystemFontOfSize(oldFont.PointSize);

	                oldFont = SenderLabel.Font;
	                SenderLabel.Font = UIFont.BoldSystemFontOfSize(oldFont.PointSize);

	                oldFont = MessageLabel.Font;
	                MessageLabel.Font = UIFont.BoldSystemFontOfSize(oldFont.PointSize);

                    oldFont = DateLabel.Font;
                    DateLabel.Font = UIFont.BoldSystemFontOfSize(oldFont.PointSize);
	            }
	            else
	            {
                    UIFont oldFont = SubjectLabel.Font;
                    SubjectLabel.Font = UIFont.SystemFontOfSize(oldFont.PointSize);

                    oldFont = SenderLabel.Font;
                    SenderLabel.Font = UIFont.SystemFontOfSize(oldFont.PointSize);

                    oldFont = MessageLabel.Font;
                    MessageLabel.Font = UIFont.SystemFontOfSize(oldFont.PointSize);

                    oldFont = DateLabel.Font;
                    DateLabel.Font = UIFont.SystemFontOfSize(oldFont.PointSize);
	            }
	        }
	    }
	}
}
