// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using GoogleAnalytics.iOS;
using MyStarStable.Common;
using System.Net;
using System.Text;
using Newtonsoft.Json;
using System.Net.Http;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace MyStarStable.iOS
{
	public partial class NewsViewController : UITableViewController
		{
		string URL = "APP/NEWS/KIMONOLABS/URL".Localize();

		public NewsViewController (IntPtr handle) : base (handle)
		{
		}



		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			UITableView table = new UITableView(View.Bounds); // defaults to Plain style

			using (var httpClient = new HttpClient ())
			{
				var response = httpClient.GetAsync (URL).Result;
			
				if (response.IsSuccessStatusCode) {
					var responseContent = response.Content;
					string contents = responseContent.ReadAsStringAsync ().Result;

					RootObject item =JsonConvert.DeserializeObject<RootObject>(contents);
					var results = item.results;


					table.Source = new NewsTableSource(results.collection1, this);
					table.IndicatorStyle = UIScrollViewIndicatorStyle.Default;
					Add (table);
				}
			}		

		}
		public override void ViewDidAppear(bool animated)
		{
			
		}
		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);



			GAI.SharedInstance.DefaultTracker.Set(GAIConstants.ScreenName, "News Screen");
			GAI.SharedInstance.DefaultTracker.Send(GAIDictionaryBuilder.CreateScreenView().Build());


		}


	}
}
