// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MyStarStable.iOS
{
	public partial class webviewOne : UIWebView
	{
		public webviewOne (IntPtr handle) : base (handle)
		{
		}
	}
}
