// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using GoogleAnalytics.iOS;

namespace MyStarStable.iOS
{
	public partial class WebViewController : UIViewController
	{
		public string webURL { get; set; }
		UIWebView webView ;

		public WebViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();


		}

		public override void ViewDidAppear(bool animated)
		{
			
			webView = new UIWebView (View.Bounds);

			View.AddSubview (webView);
			string url = webURL;
			webView.LoadRequest (new NSUrlRequest (new NSUrl (url)));
			webView.ScalesPageToFit = true;




		}

		public bool BackPressed()
		{
			webView.Dispose ();
			this.Dispose ();
			return false;
		}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);


			GAI.SharedInstance.DefaultTracker.Set(GAIConstants.ScreenName, "Webview Screen");
			GAI.SharedInstance.DefaultTracker.Send(GAIDictionaryBuilder.CreateScreenView().Build());



		}

		/*public override void ViewWillDisappear (Boolean animated)
		{
			if (this.NavigationController.ViewControllers.Length == 0) {
				// back button was pressed.  We know this is true because self is no longer
				// in the navigation stack.  
				this.DismissModalViewController(true);
			}
			webView.Dispose ();
			base.ViewWillDisappear(animated);
		}*/
	}
}
